services:
  localdb:
    image: postgres:15.1
    ports:
      - '5432:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=userName
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=dbName
  testdb:
    image: postgres:15.1
    ports:
      - '5433:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=userTest
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=dbTest
